# Generated by Django 5.2.8 on 2025-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('sale', models.BigIntegerField(blank=True, default=0)),
                ('expenses', models.BigIntegerField(blank=True, default=0)),
                ('profit', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
    ]
